# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "metrics-0.0.0-W7G4eJOgAQDBacPAeqGCaY8gV7zuddUQyikGNq7nDPds";
    path = fetchgit {
      url = "https://github.com/karlseguin/metrics.zig";
      rev = "1621f82e7ecf2b3dddf5730bf52761af354a7080";
      hash = "sha256-GUfhJv1jfyP84o6ojWBXvjoZDfnzMKB8PUn6CQMOZ7k=";
    };
  }
  {
    name = "zap-0.10.6-GoeB8y-IJAD3m9zkAkeTQalzU1NuvO072u8hA78Irdp8";
    path = fetchgit {
      url = "https://github.com/zigzap/zap";
      rev = "f6099ecec496c7ec623c5913baa5b6b5da2e883d";
      hash = "sha256-k/RuJkWgz0GaPDbrUzyrkkzHFVJ744rEHNyFKKgpCPo=";
    };
  }
]
